= Hackathon Annotations of Public data (Program)
:sectnums:
:toc: left
:doctype: book
//only works on some backends, not HTML
:showcomments:
//use style like Section 1 when referencing within the document.
:xrefstyle: short
:figure-caption: Figure
:pdf-page-size: A4

//GitHub specific settings
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

[[introduction]]
=== Introduction to Sample to Data Format

The https://github.com/bigbio/proteomics-metadata-standard/blob/master/experimental-design/README.adoc[SDRF] (Sample and Data Relationship Format) describes the sample characteristics and the relationships between samples and  data files. The information in SDRF begins by describing the samples and finishes with the names of the data files generated from the analyses of the experimental results. Here we are introducing and adapting the SDRF file format for the proteomics community.

The SDRF file is:

- A tab-delimited format where each ROW corresponds to a relation between a _Sample_ and a _Data_ file.
- Each column corresponds to an attribute/property of the _Sample_ and the value in each cell is the specific *value* of the property for a given _Sample_.

[Introduction to SDRF Slides]

[[specification]]
=== Specification and Tutorials

Before arriving to the hackathon make sure you read some documentation about SDRF project. You can find the full specification https://github.com/bigbio/proteomics-metadata-standard/blob/master/experimental-design/README.adoc[here] (takes about 10 minutes to read).

[example]
=== Annotated examples

Annotated projects can be https://github.com/bigbio/proteomics-metadata-standard/tree/master/annotated-projects[found here], you can use them as examples.
For your reference, there are also https://github.com/bigbio/proteomics-metadata-standard/tree/master/templates[template files]. Pick one according to
the organism of the annotated samples.

[[hackathon]]
=== Hackathon Actions

- Pick a project from https://www.ebi.ac.uk/pride/archive[PRIDE database].
Make sure it is not https://github.com/bigbio/proteomics-metadata-standard/tree/master/annotated-projects[already annotated].
- https://github.com/bigbio/proteomics-metadata-standard/issues/new?assignees=&labels=help+wanted%2C+project-to-annotate&template=request-project-annotation.md&title=Request+Project+Annotation+%5B+%5D[Create an issue] on Github to let the community knows that you are annotating the project.
- Annotate the project on your machine.
+
NOTE: You can validate your annotation locally using https://github.com/bigbio/sdrf-pipelines[sdrf-pipelines] (optional).

- Provide the final SDRF by https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request#changing-the-branch-range-and-destination-repository[making a pull request from a fork to the main repo]
(don't forget to make your changes in a fresh branch and not master).

- The PR is reviewed by hackathon organizers and also your annotation is checked automatically using
  https://help.github.com/en/actions/getting-started-with-github-actions/about-github-actions[Github Actions].
  If there are errors, check the error messages and update the annotation (the organizers will help you).

- Don't forget to add your name to the https://github.com/bigbio/proteomics-metadata-standard#core-contributors[list of contributors]
  when making the PR!


If you cannot create a PR, you can post the annotated file in your issue.
