= Hackathon Annotations of Public data (Program)
:sectnums:
:toc: left
:doctype: book
//only works on some backends, not HTML
:showcomments:
//use style like Section 1 when referencing within the document.
:xrefstyle: short
:figure-caption: Figure
:pdf-page-size: A4

//GitHub specific settings
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

[[introduction]]
=== Introduction to Sample to Data Format

The https://github.com/bigbio/proteomics-metadata-standard/blob/master/experimental-design/README.adoc[SDRF] (Sample and Data Relationship Format) describes the sample characteristics and the relationships between samples and  data files. The information in SDRF begins by describing the samples and finishes with the names of the data files generated from the analyses of the experimental results. Here we are introducing and adapting the SDRF file format for the proteomics community.

The SDRF file is:

- A tab-delimited format where each ROW corresponds to a relation between a _Sample_ and a _Data_ file.
- Each column corresponds to an attribute/property of the _Sample_ and the value in each cell is the specific *value* of the property for a given _Sample_.

[Introduction to SDRF Slides]

[[specification]]
=== Specification and Tutorials

Before arriving to the hackathon make sure you read some documentation about SDRF project. You can find the full specification in this https://github.com/bigbio/proteomics-metadata-standard/blob/master/experimental-design/README.adoc[link] and a [ten minutes guide here].

[example]
=== Annotated examples

A group of examples can be https://github.com/bigbio/proteomics-metadata-standard/tree/master/annotated-projects[found here]

[[hackathon]]
=== Hackathon Actions

- Pick a project for https://www.ebi.ac.uk/pride/archive[PRIDE database].
- Create an issue in Github to let the community knows that you are annotating a project https://github.com/bigbio/proteomics-metadata-standard/issues/new?assignees=&labels=help+wanted%2C+project-to-annotate&template=request-project-annotation.md&title=Request+Project+Annotation+%5B+%5D[Request Project]
- Annotate the project in your machine. Then you can provide the final SDRF doing a Pull request to the main repo or upload the file annotated in your issue.


