= SDRF-Proteomics: Crosslinking Proteomics Guidelines
:sectnums:
:toc: left
:doctype: book

== Introduction to Crosslinking Proteomics

Crosslinking mass spectrometry (XL-MS) is a powerful technique for studying protein-protein interactions and protein structures. It involves the use of chemical reagents to covalently link amino acid residues that are in close proximity in the native protein structure. These crosslinked peptides are then identified by mass spectrometry, providing valuable information about protein conformations and interactions.

== Additional Required Columns for Crosslinking Proteomics

In addition to the standard SDRF-Proteomics columns, crosslinking proteomics experiments require the following specific columns:

=== Sample Characteristics

* *characteristics[crosslinking reagent]*: This column is MANDATORY for crosslinking proteomics experiments. It describes the chemical reagent used to create covalent bonds between amino acids. Common values include:
** DSS (disuccinimidyl suberate)
** BS3 (bis(sulfosuccinimidyl)suberate)
** EDC (1-ethyl-3-(3-dimethylaminopropyl)carbodiimide)
** DSSO (disuccinimidyl sulfoxide)
** DSBU (disuccinimidyl dibutyric urea)
** PDH (pimelic acid dihydrazide)

=== Optional Recommended Columns

* *characteristics[crosslinking reagent concentration]*: This column is RECOMMENDED to specify the concentration of the crosslinking reagent used. This should include both the value and the unit (e.g., "1 mM").

* *characteristics[crosslinking reaction time]*: This column is RECOMMENDED to specify the duration of the crosslinking reaction. This should include both the value and the unit (e.g., "30 minutes").

* *characteristics[crosslinking reaction temperature]*: This column is RECOMMENDED to specify the temperature at which the crosslinking reaction was performed. This should include both the value and the unit (e.g., "25 °C").

* *characteristics[crosslinking reaction pH]*: This column is RECOMMENDED to specify the pH at which the crosslinking reaction was performed.

* *comment[crosslinker spacer length]*: This column is RECOMMENDED to specify the spacer arm length of the crosslinking reagent. This should include both the value and the unit (e.g., "11.4 Å").

* *comment[crosslink type]*: This column is RECOMMENDED to specify the type of crosslinks being analyzed. Common values include:
** Protein-protein crosslinks
** Protein-DNA crosslinks
** Protein-RNA crosslinks
** Intramolecular crosslinks
** Intermolecular crosslinks

== Example SDRF-Crosslinking File

The example file `sdrf-crosslinking.sdrf.tsv` provides a template for annotating crosslinking proteomics experiments. It includes the minimum required columns as well as the additional columns specific to crosslinking proteomics.

== Best Practices for Crosslinking Proteomics Annotation

1. Always specify the crosslinking reagent used.
2. When possible, include information about the reaction conditions (concentration, time, temperature, pH).
3. Specify the spacer arm length of the crosslinking reagent, as this determines the maximum distance between crosslinked residues.
4. Indicate whether the experiment focuses on intramolecular crosslinks, intermolecular crosslinks, or both.
5. For studies involving protein complexes, consider including information about the complex composition and stoichiometry.
6. If specialized data analysis software was used, document this in the methods section.