= PRIDE Experiment Design Project
:sectnums:
:toc: left
:doctype: book
//only works on some backends, not HTML
:showcomments:
//use style like Section 1 when referencing within the document.
:xrefstyle: short
:figure-caption: Figure
:pdf-page-size: A4

//GitHub specific settings
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

[[introduction]]
== Increasing the amount of metadata in PRIDE datasets

The *PRIDE Experiment Design* project aim to define a set of guidelines and file formats to support the annotation of Experiment design of PRIDE submissions. The PRIDE Team, advocates for open access and reuse of proteomics datasets and works towards providing concrete solutions to achieve this. Our goal with the *Experiment Design format* is to assure maximum reusability of the deposited data. Our work aim to define the minimum information required to report the proteomics Experiment design, enabling the used and reused of the deposited data by the proteomics community.

The following _Use Cases_ would be consider to design the PRIDE Experiment design data format:

- The Experiment design file format will complement the http://ftp.pride.ebi.ac.uk/pride/resources/schema/proteomexchange/proteomeXchange-1.4.0.xsd[proteomeXchange.xml] file format implemented by http://www.proteomexchange.org/[ProteomeXchange] to capture the minimum metadata about a Proteomics dataset. The ProteomeXchange submission format XML file format is explained in details http://www.proteomexchange.org/docs/guidelines_px.pdf[here].

- The Experiment design format SHOULD enable submitters and curators to annotate the proteomics dataset from the sample metadata (e.g. Organism) to the Experiment protocol (e.g. Instrument model).

- The Experiment design format SHOULD enable the proteomics and bioinformatics community the automatic reanalysis of public proteomics data. The Experiment design aim the reanalysis of Quantitative data and a better representation of Quantitative data in public repositories.


[[notational-conventions]]
== Notational Conventions

The key words “MUST”, “MUST NOT”, “REQUIRED”, “SHALL”, “SHALL NOT”, “SHOULD”, “SHOULD NOT”, “RECOMMENDED”, “MAY”, and “OPTIONAL” are to be interpreted as described in RFC-2119 <<bradner-1997, (Bradner 1997)>>.

[[ontologies]]
== Ontologies

The Experiment Design format would be based on ontology terms (e.g. UNIMOD-35). An _ontology_ encompasses a representation, formal naming and definition of the categories, properties and relations between the concepts, data and entities that substantiate one, many or all domains of discourse. All Ontologies used in the PRIDE Experiment Design format MUST be index in the https://www.ebi.ac.uk/ols/index[Ontology Lockup Service]. The current ontologies accepted by the format are:

- https://www.ebi.ac.uk/ols/ontologies/pride[PRIDE Ontology]

- https://www.ebi.ac.uk/ols/ontologies/ms[Mass Spectrometry Ontology]

- https://www.ebi.ac.uk/ols/ontologies/efo[Experimental Factor Ontology]

- https://www.ebi.ac.uk/ols/ontologies/unimod[Unimod protein modification database for mass spectrometry]

WARNING: If you you are contributing with the following guidelines and file format, and WOULD like to add another ontology; please modified the list with a Pull Request.

[[format-structure]]
== Experiment design structure

The current project is focus in three main topics:

 - https://github.com/PRIDE-Archive/pride-metadata-standard/tree/master/experimental-design[Experimental Design]
 - https://github.com/PRIDE-Archive/pride-metadata-standard/tree/master/technical-metadata/msrun-metadata[MSRun Metadata]

[[core-contributors]]
== Core contributors and Collaborators

The Current Project is run by PRIDE Team in collaboration with other external groups:

- Yasset Perez-Riverol (PRIDE Team, European Bioinformatics Institute - EMBL-EBI)
- Mathias Walzer (PRIDE Team, European Bioinformatics Institute - EMBL-EBI)
- Andrew Jarnuczak (PRIDE Team, European Bioinformatics Institute - EMBL-EBI)
- Timo Sachsenberg (OpenMS Team, Tübingen University)
- Oliver Alka (OpenMS Team, Tübingen University)
- Julianus Pfeuffer (OpenMS Team, Tübingen University)
- Mark Vaudel (PeptideShaker, University of Bergen)
- Harald Barsnes (PeptideShaker, University of Bergen)
- Niels Hulstaert (Compomics, University of Gent)
- Lennart Martens (Compomics, University of Gent)
- Expression Atlas Team (European Bioinformatics Institute - EMBL-EBI)


IMPORTANT: If you contribute with the following specification, please make sure to add your name to the list of contributors.



