= Proteomics Experiment Design Project
:sectnums:
:toc: left
:doctype: book
//only works on some backends, not HTML
:showcomments:
//use style like Section 1 when referencing within the document.
:xrefstyle: short
:figure-caption: Figure
:pdf-page-size: A4

//GitHub specific settings
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

[[introduction]]
== Improving metadata annotation of Proteomics datasets

The *Proteomics Experiment Design* project aims to define a set of guidelines and file formats to support the annotation of experiment design in Proteomics submissions. The Proteomics Team advocates for open access and reuse of proteomics datasets and works towards providing concrete solutions to achieve this. Our goal with the *Experiment Design format* is to enssure maximum reusability of the deposited data. Our work aims to define the minimum information required to report the proteomics experiment design, enabling the use and reuse of the deposited data by the proteomics community.

The following _Use Cases_ should be considered to design the Proteomic Experiment design data format:

- The experiment design file format will complement the http://ftp.pride.ebi.ac.uk/pride/resources/schema/proteomexchange/proteomeXchange-1.4.0.xsd[proteomeXchange.xml] file format implemented by http://www.proteomexchange.org/[ProteomeXchange] to capture the minimum metadata on a Proteomics dataset. The ProteomeXchange submission XML file format is detailed http://www.proteomexchange.org/docs/guidelines_px.pdf[here].

- The experiment design format SHOULD enable submitters and curators to annotate the proteomics dataset from the sample metadata (e.g. Organism) to the experiment protocol (e.g. Instrument model).

- The Experiment design format SHOULD facilitate the automatic reanalysis of public proteomics data. The experiment design aims to enable the reanalysis of quantitative data and provide a better representation of quantitative data in public repositories.


[[notational-conventions]]
== Notational conventions

The key words “MUST”, “MUST NOT”, “REQUIRED”, “SHALL”, “SHALL NOT”, “SHOULD”, “SHOULD NOT”, “RECOMMENDED”, “MAY”, and “OPTIONAL” are to be interpreted as described in https://www.rfc-archive.org/getrfc?rfc=2119[RFC-2119 (Bradner 1997)].

[[ontologies]]
== Ontologies

The Experiment Design format should be based on ontology terms (e.g. UNIMOD-35). An _ontology_ encompasses a representation, formal naming and definition of the categories, properties and relations between the concepts, data and entities that substantiate one, many or all domains of discourse. All Ontologies used in the Proteomic Experiment Design format MUST be indexed in the https://www.ebi.ac.uk/ols/index[Ontology Lockup Service]. The current ontologies supported in the format are:

- https://www.ebi.ac.uk/ols/ontologies/pride[PRIDE Ontology]
- https://www.ebi.ac.uk/ols/ontologies/ms[Mass Spectrometry Ontology]
- https://www.ebi.ac.uk/ols/ontologies/efo[Experimental Factor Ontology]
- https://www.ebi.ac.uk/ols/ontologies/unimod[Unimod protein modification database for mass spectrometry]
- https://www.ebi.ac.uk/ols/ontologies/clo[Cell line ontology]
- https://www.ebi.ac.uk/ols/ontologies/FBbt[Drosophila anatomy ontology]
- https://www.ebi.ac.uk/ols/ontologies/cl[Cell ontology]
- https://www.ebi.ac.uk/ols/ontologies/po[Plant ontology]
- https://www.ebi.ac.uk/ols/ontologies/uberon[Uber-anatomy ontology]
- https://www.ebi.ac.uk/ols/ontologies/zfa[Zebrafish anatomy and development ontology]
- https://www.ebi.ac.uk/ols/ontologies/zfs[Zebrafish developmental stages ontology]
- https://www.ebi.ac.uk/ols/ontologies/eo[Plant Environment Ontology]
- https://www.ebi.ac.uk/ols/ontologies/Fbdv[FlyBase Developmental Ontology]
- https://www.ebi.ac.uk/ols/ontologies/RS[Rat Strain Ontology]
- https://www.ebi.ac.uk/ols/ontologies/ChEBI[Chemical Entitities of Biological Interest Ontology]
- https://www.ebi.ac.uk/ols/ontologies/NCBITAXON[NCBI organismal classification]

WARNING: If you you are contributing with the following guidelines and file format, and WOULD like to add another ontology; please modify the list with a Pull Request.

[[format-structure]]
== Sample experiment design structure (SDRF)

 - https://github.com/bigbio/pride-metadata-standard/tree/master/experimental-design[Experimental Design]

[[How-to-contribute]]
== How to contribute

External contributors, researchers and the proteomics community are more than welcome to contribute with this project.

Contribute with the specification: you can contribute with the specification with ideas or refinements by adding an issue into the https://github.com/bigbio/proteomics-metadata-standard/issues[issue tracker] or performing a PR.

[[annotate-project]]
=== Annotate Public dataset :fireworks:

In the https://github.com/bigbio/proteomics-metadata-standard/tree/master/annotated-projects[annotate projects] folder the user can see different public datasets that has been annotated by the contributors. If you would like to join to these efforts, make a Fork of this repo and perform a pull request (PR) with your annotated project. If you don't have a project in mind, you can take one project from the https://github.com/bigbio/proteomics-metadata-standard/issues[issues] and perform the annotation.

Annotate a dataset in 5 steps:

1- Read the https://github.com/bigbio/proteomics-metadata-standard/tree/master/experimental-design[SDRF specification]

2- Depending on the type of dataset, chose the appropriate https://github.com/bigbio/proteomics-metadata-standard/tree/master/experimental-design#sdrf-templates[sample template]

3- Annotate the the corresponding ProteomeXchange PX following the guidelines

4- Validate your sdrf:

In order to validate your sdrf, you can install the sdrfcheker tool in python

```bash
pip install sdrfcheker
```

validate the sdrf

```bash
python sdrfchecker.py validate-sdrf --sdrf_file sdrf.txt
```

You can read more about the validator https://github.com/bigbio/sdrfcheck[here]

5- Fork the current repository add a folder with the ProteomeXchange accession and the annotated sdrf.txt

[[core-contributors]]
== Core contributors and collaborators

The project is run by different groups:

- Yasset Perez-Riverol (PRIDE Team, European Bioinformatics Institute - EMBL-EBI, U.K.)
- Timo Sachsenberg (OpenMS Team, Tübingen University, Germany)
- Anja Fullgrabe (ExpressionAtlas Team, European Bioinformatics Institute - EMBL-EBI, U.K.)
- Nancy George (ExpressionAtlas Team, European Bioinformatics Institute - EMBL-EBI, U.K.)
- Mathias Walzer (PRIDE Team, European Bioinformatics Institute - EMBL-EBI, U.K.)
- Pablo Moreno (ExpressionAtlas Team, European Bioinformatics Institute - EMBL-EBI, U.K.)
- Oliver Alka (OpenMS Team, Tübingen University, Germany)
- Julianus Pfeuffer (OpenMS Team, Tübingen University, Germany)
- Marc Vaudel (University of Bergen, Norway)
- Harald Barsnes (University of Bergen, Norway)
- Niels Hulstaert (Compomics, University of Gent, Belgium)
- Lennart Martens (Compomics, University of Gent, Belgium)
- Expression Atlas Team (European Bioinformatics Institute - EMBL-EBI, U.K.)


IMPORTANT: If you contribute with the following specification, please make sure to add your name to the list of contributors.


[[code-of-conduct]]
== Code of Conduct

As part of our efforts toward delivering open and inclusive science, we follow the [Contributor Convenant](https://www.contributor-covenant.org) [Code of Conduct for Open Source Projects](docs/CODE_OF_CONDUCT.md).


