= PRIDE Experimental Design

The *PRIDE Experimental Design* project aim to define a set of guidelines and file formats to support the annotation of experimental design of PRIDE submissions. The PRIDE Team, advocates for open access and reuse of proteomics datasets and works towards providing concrete solutions to achieve this. Our goal with the *Experimental Design format* is to assure maximum reusability of the deposited data. Our work aim to define the minimum information required to report the proteomics experimental design, enabling the used and reused of the deposited data by the proteomics community.

The following use cases would be consider to design the PRIDE experimental design data format:

- The experimental design file format will complement the http://ftp.pride.ebi.ac.uk/pride/resources/schema/proteomexchange/proteomeXchange-1.4.0.xsd[proteomeXchange.xml] file format implemented by http://www.proteomexchange.org/[ProteomeXchange] to capture the minimum metadata about a Proteomics dataset. The



*Core Contributors and Collaborators:*

- Mathias Walzer (PRIDE Team, European Bioinformatics Institute - EMBL-EBI)
- Andrew Jarnuczak (PRIDE Team, European Bioinformatics Institute - EMBL-EBI)
- Timo Sachsenberg (OpenMS Team, Tübingen University)
- Oliver Alka (OpenMS Team, Tübingen University)
- Julianus Pfeuffer (OpenMS Team, Tübingen University)
- Mark Vaudel (PeptideShaker, University of Bergen)
- Expression Atlas Team (European Bioinformatics Institute - EMBL-EBI)

