= Templates Status for SDRF-Proteomics
:sectnums:
:toc: left
:doctype: book
//only works on some backends, not HTML
:showcomments:
//use style like Section 1 when referencing within the document.
:xrefstyle: short
:figure-caption: Figure
:pdf-page-size: A4

//GitHub specific settings
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Released Templates

The following templates have been officially released and are ready for use:

=== Core Templates

Basic organism-based templates for standard proteomics experiments:

- **Default**: Basic template for any proteomics experiment
- **Human**: Template with human-specific metadata fields
- **Cell Line**: Basic cell line template
- **Vertebrates**: Template for vertebrate organisms
- **Invertebrates**: Template for invertebrate organisms
- **Plants**: Template for plant organisms

=== Cell Lines Template

Comprehensive guidance on cell line annotation using Cellosaurus as the primary resource for standardized cell line identification and metadata.

- link:./templates/cell-lines/README.adoc[Cell Lines Template Documentation]

== Templates Under Development

The following specialized templates are currently under development. They are available for early adoption and feedback, but may undergo changes before final release.

=== Affinity Proteomics

Template for affinity-based proteomics including Olink (PEA), SomaScan, Luminex, RPPA, and immunoaffinity-MS experiments.

- link:./templates/affinity-proteomics/README.adoc[Affinity Proteomics Template (Draft)]
- Status: Under development

=== Crosslinking Mass Spectrometry

Template for crosslinking mass spectrometry (XL-MS) structural proteomics experiments.

- link:./templates/crosslinking/README.adoc[Crosslinking Template (Draft)]
- Status: Under development

=== Immunopeptidomics

Template for MHC-bound peptide identification experiments, including HLA typing annotation.

- link:./templates/immunopeptidomics/README.adoc[Immunopeptidomics Template (Draft)]
- Status: Under development

=== Metaproteomics

Template for microbial community proteomics experiments.

- link:./templates/metaproteomics/README.adoc[Metaproteomics Template (Draft)]
- Status: Under development

Metaproteomics experiments are a special use case for the organism under study because multiple species/organisms would be in the sample. In those cases the _characteristics[organism]_ will not be unique. Transcriptomics resources use the value `mixed`, but it is an ambiguous term that makes the sample metadata unreadable.

=== Single Cell Proteomics

Template for single cell proteomics (SCP) experiments.

- link:./templates/single-cell/README.adoc[Single Cell Proteomics Template (Draft)]
- Status: Under development

== Templates Under Discussion

In this section, we describe and list all the templates that are actively under discussion by this initiative. In cases where some ongoing discussion is still happening about how to handle a particular analytical method or type of dataset, the link to the issue/issues in GitHub is provided. Please, if you want to discuss a particular template you can create an https://github.com/bigbio/proteomics-metadata-standard/issues[issue in GitHub] and explain the problem or use case to be discussed.

=== MS-Imaging Datasets

Discussions about MS-Imaging representation can be found in the https://github.com/bigbio/proteomics-metadata-standard/issues/451[following issue]. Some problems of the current model that need to be refined for Imaging datasets:

*Metadata that does not apply to MSI*:

- Reduction and Alkylation: Was suggested to be mandatory. In that case, for most MSI studies it would be "not applicable"
- Fraction identifier: this is never done in MSI - Therefore, I would prefer "not applicable" in contrast to classical unfractionated proteomics experiments, where one would set all fractions to "1"
- MS2/Database search related terms are not mandatory currently; therefore, they could just be ignored for MSI data.

*MSI specific things*

- File type: The open standard format imzML is a composite file type consisting of two files: imzML + ibd - In the current annotation I only used one line and referenced only the imzML subfile but not ibd. This makes it easier to annotate and understand the metadata but might be problematic for some (automated) applications?

- Multiple samples per run: Multiple tissues can be placed onto one slide. As the technique is label-free and spatially resolved the samples can be distinguished by their position on the slide/plate. This might require an additional graphic that shows an ID of each sample or the center of the sample in x and y coordinates.
All files in PXD011104 have multiple samples, I have picked only one of the files to annotate a first simple example. I just numbered the 4 tissue sections (largest image shown here: https://ftp.pride.ebi.ac.uk/pride/data/archive/2020/08/PXD011104/Information-gastricmousemodel-MALDI-TOF.docx) from left to right as "position on slide": 1,2,3,4. This would require an additional image that shows the position IDs.

*(Potential) additional MSI metadata columns*

- Origin of cleavage agent: Autolysis peptides of proteases are important for calibration/QC/contaminant removal in MSI, as they differ e.g. bovine vs. porcine it would be helpful to include this information
- Matrix: For MALDI experiments, the name/chemical composition of the matrix is helpful to remove the corresponding peaks during analysis.
- Ionization source: It is quite common to customize ionization sources, then the available "instrument" terms do not reflect the truth anymore. Adding the Ionization source as separate column might be necessary.
- Analyte: One of the MSI datasets I annotated measured phospholipids, another measured N-glycans.

=== Derived Samples (such as patient-derived xenografts)

While a first prototype of the specification is now https://github.com/bigbio/proteomics-metadata-standard/tree/master/sdrf-proteomics#derived-samples-such-as-patient-derived-xenografts[formalized in the specification] still some issues are pending:

- Full examples with multiple species, type of mixtures etc. are necessary.
- Relation between the samples should be captured. In a xenograft dataset, the description of sample 1 and sample 2 should be provided. It is not clear how to perform that (repeated columns) or different SDRF.

=== Turnover and TMT Datasets

- Turnover experiments can contain multiple labels, for example, TMT (for quantification) and SILAC for turnover differential expression. An existing project https://github.com/bigbio/proteomics-metadata-standard/tree/master/annotated-projects/PXD017710[was originally annotated as two independent datasets], however an ongoing discussion is defining what is the best way to define this type of experiments.

== Contributing

If you would like to contribute to template development or propose a new template:

1. Open an issue on https://github.com/bigbio/proteomics-metadata-standard/issues[GitHub] describing the experiment type
2. Discuss requirements with the community
3. Submit a pull request with the template following the established structure
