= Use cases status for MAGE-TAB for proteomics
:sectnums:
:toc: left
:doctype: book
//only works on some backends, not HTML
:showcomments:
//use style like Section 1 when referencing within the document.
:xrefstyle: short
:figure-caption: Figure
:pdf-page-size: A4

//GitHub specific settings
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Use cases supported by MAGE-TAB for proteomics

In this section we describe and list all the uses cases already supported by MAGE-TAB for proteomics file format and the analytical techniques. In addition, we include examples and for each analytical method and use case supported.

NOTE: In cases where some ongoing discussion is still happening about how to handle a particular analytical method or type of dataset. The link to the issue/issues in github is provided. Please, if you want to discuss a particular use case you can create an [issue in github](https://github.com/bigbio/proteomics-metadata-standard/issues) and explain the problem or use case to be disscuss.


