= SDRF-Proteomics: Immunopeptidomics Guidelines
:sectnums:
:toc: left
:doctype: book

== Introduction to Immunopeptidomics

Immunopeptidomics is a specialized field of proteomics that focuses on the identification and characterization of peptides presented by major histocompatibility complex (MHC) molecules on the cell surface. These peptides play a crucial role in the immune system's ability to recognize and respond to foreign or abnormal cells.

== Additional Required Columns for Immunopeptidomics

In addition to the standard SDRF-Proteomics columns, immunopeptidomics experiments require the following specific columns:

=== Sample Characteristics

* *characteristics[immunopeptidome enrichment method]*: This column is MANDATORY for immunopeptidomics experiments. It describes the method used to enrich for MHC-bound peptides. Common values include:
** MHC-I immunoprecipitation
** MHC-II immunoprecipitation
** Acid elution
** Combined MHC-I and MHC-II immunoprecipitation

=== Optional Recommended Columns

* *characteristics[MHC alleles]*: This column is RECOMMENDED to specify the MHC alleles present in the sample. This information is particularly important for interpreting the results of immunopeptidomics experiments.

* *characteristics[antibody used for immunoprecipitation]*: This column is RECOMMENDED to specify the antibody used for MHC immunoprecipitation. Common values include W6/32 (for MHC-I) or L243 (for MHC-II).

* *comment[peptide length range]*: This column is RECOMMENDED to specify the length range of peptides identified in the experiment. This is particularly relevant for distinguishing between MHC-I (typically 8-12 amino acids) and MHC-II (typically 12-25 amino acids) bound peptides.

== Example SDRF-Immunopeptidomics File

The example file `sdrf-immunopeptidomics.sdrf.tsv` provides a template for annotating immunopeptidomics experiments. It includes the minimum required columns as well as the additional columns specific to immunopeptidomics.

== Best Practices for Immunopeptidomics Annotation

1. Always specify the immunopeptidome enrichment method used.
2. When possible, include information about the MHC alleles present in the sample.
3. For studies involving multiple MHC alleles, consider using separate rows for each allele if peptides can be specifically assigned.
4. Include details about the antibody used for immunoprecipitation.
5. Specify the peptide length range to help distinguish between MHC-I and MHC-II bound peptides.