= SDRF-Proteomics: SomaScan Template
:sectnums:
:toc: left
:doctype: book
:showcomments:
:xrefstyle: short
:figure-caption: Figure
:pdf-page-size: A4

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

[[status]]
== Status of this Template

This document provides guidelines for annotating SomaScan aptamer-based proteomics experiments in SDRF-Proteomics format.

**Type:** Platform-Specific Template (extends affinity-proteomics)

**Status:** Released

**Version:** 1.0.0 - 2026-01

[[abstract]]
== Abstract

SomaScan is an aptamer-based proteomics platform developed by SomaLogic that uses Slow Off-rate Modified Aptamers (SOMAmer) reagents to measure protein levels. This template extends the affinity-proteomics template with SomaScan-specific metadata fields for menu version, sample matrix, and normalization methods.

[[hierarchy]]
== Template Hierarchy

[source]
----
base
  └── affinity-proteomics
        └── somascan (THIS TEMPLATE)
----

[[usage]]
== Usage

[source]
----
#template=affinity-proteomics; version=v1.1.0
#template=somascan; version=v1.0.0
#template=human; version=v1.1.0  (optional, for human samples)
----

[[checklist]]
== SomaScan-Specific Columns

In addition to all columns from link:../affinity-proteomics/README.adoc[affinity-proteomics], the following SomaScan-specific columns are available:

=== Required for SomaScan

ifdef::backend-html5[]
++++
<table class="tableblock frame-all grid-all stretch requirements-table">
<thead>
<tr><th>Column</th><th>Requirement</th><th>Description</th><th>Example Values</th></tr>
</thead>
<tbody>
<tr>
<td><code>comment[somascan menu]</code></td>
<td><span class="required-badge">REQUIRED</span></td>
<td>SomaScan assay menu (number of aptamers)</td>
<td>SomaScan 5K, SomaScan 7K, SomaScan 11K</td>
</tr>
<tr>
<td><code>comment[somascan platform]</code></td>
<td><span class="required-badge">REQUIRED</span></td>
<td>SomaScan platform version</td>
<td>SomaScan Assay v4, SomaScan Assay v4.1</td>
</tr>
</tbody>
</table>
++++
endif::[]

ifndef::backend-html5[]
[cols="2,1,2,2", options="header"]
|===
|Column |Requirement |Description |Example Values

|comment[somascan menu] |REQUIRED |SomaScan assay menu |SomaScan 5K, SomaScan 7K, SomaScan 11K
|comment[somascan platform] |REQUIRED |SomaScan platform version |SomaScan Assay v4, SomaScan Assay v4.1
|===
endif::[]

=== Recommended for SomaScan

ifdef::backend-html5[]
++++
<table class="tableblock frame-all grid-all stretch requirements-table">
<thead>
<tr><th>Column</th><th>Requirement</th><th>Description</th><th>Example Values</th></tr>
</thead>
<tbody>
<tr>
<td><code>comment[sample matrix]</code></td>
<td><span class="recommended-badge">RECOMMENDED</span></td>
<td>Sample matrix type (affects calibration)</td>
<td>plasma, serum, EDTA plasma, CSF</td>
</tr>
<tr>
<td><code>comment[dilution]</code></td>
<td><span class="recommended-badge">RECOMMENDED</span></td>
<td>Sample dilution factor used</td>
<td>0.005%, 0.5%, 20%, 40%</td>
</tr>
<tr>
<td><code>comment[normalization method]</code></td>
<td><span class="recommended-badge">RECOMMENDED</span></td>
<td>Normalization method applied to RFU values</td>
<td>hybridization control normalized, median normalized, ANML</td>
</tr>
<tr>
<td><code>comment[QC flag]</code></td>
<td><span class="optional-badge">OPTIONAL</span></td>
<td>Quality control flag</td>
<td>PASS, FLAG, FAIL</td>
</tr>
<tr>
<td><code>comment[somascan lot number]</code></td>
<td><span class="optional-badge">OPTIONAL</span></td>
<td>Reagent lot number</td>
<td>SS-2023-001</td>
</tr>
</tbody>
</table>
++++
endif::[]

ifndef::backend-html5[]
[cols="2,1,2,2", options="header"]
|===
|Column |Requirement |Description |Example Values

|comment[sample matrix] |RECOMMENDED |Sample matrix type |plasma, serum, EDTA plasma
|comment[dilution] |RECOMMENDED |Dilution factor |0.005%, 0.5%, 20%, 40%
|comment[normalization method] |RECOMMENDED |Normalization method |median normalized, ANML
|comment[QC flag] |OPTIONAL |Quality control flag |PASS, FLAG, FAIL
|comment[somascan lot number] |OPTIONAL |Reagent lot number |SS-2023-001
|===
endif::[]

[[somascan-menus]]
== SomaScan Assay Menus

SomaScan offers different menu sizes based on the number of protein targets:

=== Current Menus

* **SomaScan 7K**: ~7,000 protein targets (current standard)
* **SomaScan 11K**: ~11,000 protein targets (expanded panel)

=== Legacy Menus

* **SomaScan 1.1K**: ~1,100 protein targets
* **SomaScan 1.3K**: ~1,300 protein targets
* **SomaScan 5K**: ~5,000 protein targets

[[technology-type]]
== Technology Type

For SomaScan experiments, use:

`technology type` = `protein expression profiling by aptamer array`

[[quantification]]
== Quantification

SomaScan uses **RFU (Relative Fluorescence Units)**:

* RFU is a measure of fluorescence intensity proportional to protein concentration
* Higher RFU = higher protein concentration
* RFU values require normalization for cross-sample comparisons
* Standard normalization includes hybridization control, median, and plate scaling

Always set:

`comment[quantification unit]` = `RFU`

[[sample-matrix]]
== Sample Matrix

The sample matrix is critical for SomaScan assays because calibration and expected ranges differ by matrix type:

* **EDTA plasma**: Preferred matrix, most validated
* **Serum**: Commonly used alternative
* **Citrate/Heparin plasma**: Less common
* **CSF**: Specialized protocols
* **Cell/Tissue lysates**: Research applications

[[normalization]]
== Normalization Methods

SomaScan data typically undergoes multiple normalization steps:

1. **Hybridization control normalization**: Corrects for hybridization variation
2. **Median normalization**: Scales samples to common median
3. **Plate scale normalization**: Corrects for plate-to-plate variation
4. **Calibration**: Applies standard curve corrections
5. **ANML (Adaptive Normalization by Maximum Likelihood)**: Advanced cross-study normalization

[[example]]
== Example SDRF

ifndef::env-github[]
++++
<div class="sdrf-example-table">
<table>
<thead>
<tr>
<th class="sample-col">source name</th>
<th class="sample-col">characteristics[organism]</th>
<th class="sample-col">characteristics[organism part]</th>
<th class="sample-col">characteristics[disease]</th>
<th class="data-col">assay name</th>
<th class="data-col">technology type</th>
<th class="data-col">comment[instrument]</th>
<th class="data-col">comment[somascan menu]</th>
<th class="data-col">comment[somascan platform]</th>
<th class="data-col">comment[quantification unit]</th>
<th class="data-col">comment[sample matrix]</th>
<th class="data-col">comment[normalization method]</th>
<th class="data-col">comment[data file]</th>
</tr>
</thead>
<tbody>
<tr>
<td class="sample-col">patient_001</td>
<td class="sample-col">homo sapiens</td>
<td class="sample-col">blood plasma</td>
<td class="sample-col">type 2 diabetes mellitus</td>
<td class="data-col">SL0001</td>
<td class="data-col">protein expression profiling by aptamer array</td>
<td class="data-col">SomaScan Assay 7K</td>
<td class="data-col">SomaScan 7K</td>
<td class="data-col">SomaScan Assay v4.1</td>
<td class="data-col">RFU</td>
<td class="data-col">EDTA plasma</td>
<td class="data-col">adaptive normalization by maximum likelihood (ANML)</td>
<td class="data-col">somascan_results.adat</td>
</tr>
<tr>
<td class="sample-col">patient_002</td>
<td class="sample-col">homo sapiens</td>
<td class="sample-col">blood plasma</td>
<td class="sample-col">normal</td>
<td class="data-col">SL0002</td>
<td class="data-col">protein expression profiling by aptamer array</td>
<td class="data-col">SomaScan Assay 7K</td>
<td class="data-col">SomaScan 7K</td>
<td class="data-col">SomaScan Assay v4.1</td>
<td class="data-col">RFU</td>
<td class="data-col">EDTA plasma</td>
<td class="data-col">adaptive normalization by maximum likelihood (ANML)</td>
<td class="data-col">somascan_results.adat</td>
</tr>
</tbody>
</table>
<div class="sdrf-legend">
<span class="legend-item"><span class="legend-color sample-bg"></span> Sample metadata</span>
<span class="legend-item"><span class="legend-color data-bg"></span> Data file metadata</span>
</div>
</div>
++++
endif::[]

ifdef::env-github[]
[cols="1,1,1,1,1,1,1,1,1,1,1,1,1", options="header"]
|===
|source name |characteristics[organism] |characteristics[organism part] |characteristics[disease] |assay name |technology type |comment[instrument] |comment[somascan menu] |comment[somascan platform] |comment[quantification unit] |comment[sample matrix] |comment[normalization method] |comment[data file]

|patient_001 |homo sapiens |blood plasma |type 2 diabetes mellitus |SL0001 |protein expression profiling by aptamer array |SomaScan Assay 7K |SomaScan 7K |SomaScan Assay v4.1 |RFU |EDTA plasma |adaptive normalization by maximum likelihood (ANML) |somascan_results.adat
|patient_002 |homo sapiens |blood plasma |normal |SL0002 |protein expression profiling by aptamer array |SomaScan Assay 7K |SomaScan 7K |SomaScan Assay v4.1 |RFU |EDTA plasma |adaptive normalization by maximum likelihood (ANML) |somascan_results.adat
|===
endif::[]

[[data-files]]
== Data File Formats

SomaScan data files:

* **ADAT**: Native SomaScan format (annotated data file)
* **CSV/TSV**: Tabular exports of RFU values

The `assay name` column must match the **SampleId** column in the ADAT file.

[[validation]]
== Validation

[source,bash]
----
pip install sdrf-pipelines
parse_sdrf validate-sdrf --sdrf_file your_file.sdrf.tsv --template somascan
----

[[template-file]]
== Template File

- link:somascan-template.sdrf.tsv[somascan-template.sdrf.tsv]

[[related-templates]]
== Related Templates

* link:../affinity-proteomics/README.adoc[Affinity Proteomics] - Parent template
* link:../olink/README.adoc[Olink Template] - Alternative affinity platform
* link:../human/README.adoc[Human Template] - Human sample metadata

[[references]]
== References

- Gold L, et al. (2010) Aptamer-based multiplexed proteomic technology for biomarker discovery. PLoS ONE.
- SomaLogic: https://somalogic.com/
- SomaScan Technical Documentation: https://somalogic.com/somascan-platform/
