name: base
description: Base SDRF template with shared columns inherited by all proteomics templates. This is a construction artifact and cannot be used directly - use ms-proteomics or affinity-proteomics instead.
version: 1.1.0
usable_alone: false
validators:
  - validator_name: trailing_whitespace_validator
    params: {}
  - validator_name: column_order
    params: {}
  - validator_name: empty_cells
    params: {}
  - validator_name: combination_of_columns_no_duplicate_validator
    params:
      column_name:
        - source name
        - assay name
      column_name_warning:
        - source name
        - assay name
columns:
  - name: source name
    description: Unique identifier for the biological sample
    requirement: required
    allow_not_applicable: false
    allow_not_available: false

  - name: characteristics[organism]
    description: Species of the sample using NCBI Taxonomy
    requirement: required
    allow_not_applicable: true
    allow_not_available: false
    validators:
      - validator_name: ontology
        params:
          ontologies:
            - ncbitaxon
          error_level: error
          description: The organism should be a valid NCBI Taxonomy term
          examples:
            - homo sapiens
            - mus musculus
            - rattus norvegicus
            - saccharomyces cerevisiae

  - name: characteristics[organism part]
    description: Anatomical part of the organism from which sample was derived
    requirement: required
    cardinality: multiple
    allow_not_applicable: true
    allow_not_available: true
    validators:
      - validator_name: ontology
        params:
          ontologies:
            - uberon
            - bto
          error_level: warning
          description: The organism part should be a valid UBERON or BTO term
          examples:
            - liver
            - brain
            - heart
            - blood

  - name: characteristics[cell type]
    description: Cell type of the sample
    requirement: recommended
    cardinality: multiple
    allow_not_applicable: true
    allow_not_available: true
    validators:
      - validator_name: ontology
        params:
          ontologies:
            - cl
            - bto
            - clo
          error_level: warning
          description: The cell type should be a valid Cell Ontology (CL), BRENDA Tissue Ontology (BTO), or Cell Line Ontology (CLO) term
          examples:
            - hepatocyte
            - neuron
            - fibroblast
            - T cell

  - name: characteristics[biological replicate]
    description: Identifier for the biological replicate (integer starting from 1, or 'pooled' for pooled samples)
    requirement: required
    allow_not_applicable: false
    allow_not_available: false
    allow_pooled: true
    validators:
      - validator_name: pattern
        params:
          pattern: ^\d+$|^pooled$
          description: Biological replicate should be an integer or 'pooled' for pooled reference samples
          examples:
            - 1
            - 2
            - pooled

  - name: assay name
    description: Unique identifier for the data acquisition run
    requirement: required
    allow_not_applicable: false
    allow_not_available: false

  - name: technology type
    description: Type of technology used
    requirement: required
    allow_not_applicable: false
    allow_not_available: false
    validators:
      - validator_name: single_cardinality_validator
        params: {}
      - validator_name: values
        params:
          values:
            - proteomic profiling by mass spectrometry
            - protein expression profiling by antibody array
            - protein expression profiling by aptamer array

  - name: comment[instrument]
    description: Instrument used for data acquisition (MS instrument or affinity platform)
    requirement: required
    allow_not_applicable: false
    allow_not_available: false
    validators:
      - validator_name: single_cardinality_validator
        params: {}
      - validator_name: ontology
        params:
          ontologies:
            - ms
            - pride
          error_level: warning
          description: The instrument should be a valid MS or PRIDE ontology term

  - name: comment[technical replicate]
    description: Identifier for the technical replicate (integer starting from 1)
    requirement: recommended
    type: integer
    allow_not_applicable: false
    allow_not_available: false

  - name: comment[data file]
    description: Name of the raw data file
    requirement: required
    allow_not_applicable: false
    allow_not_available: false

  - name: comment[modification parameters]
    description: Post-translational modifications searched
    requirement: recommended
    cardinality: multiple
    allow_not_applicable: true
    allow_not_available: true
    validators:
      - validator_name: ontology
        params:
          ontologies:
            - unimod
          error_level: warning
          description: The modification parameters should be valid Unimod terms
          examples:
            - NT=Oxidation;MT=Variable;TA=M;AC=Unimod:35
            - NT=Carbamidomethyl;TA=C;MT=fixed;AC=UNIMOD:4
