name: default
description: Default SDRF template for general proteomics experiments
version: 1.1.0
extends: minimum
columns:
  - name: characteristics[disease]
    description: Disease state of the sample
    requirement: required
    allow_not_applicable: true
    allow_not_available: true
    validators:
      - validator_name: ontology
        params:
          ontologies:
            - mondo
            - efo
            - doid
          error_level: warning
          description: The disease should be a valid MONDO, EFO, or DOID ontology term. Use 'normal' for healthy samples.
          examples:
            - normal
            - breast cancer
            - diabetes mellitus
            - Alzheimer disease
